/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class RailLinesMapRuntimeModule extends AbstractRailLinesMapRuntimeModule {
}
