/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getSrc <em>Src</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getDst <em>Dst</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getLength <em>Length</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getGauge <em>Gauge</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getConnection()
 * @model
 * @generated
 */
public interface Connection extends EObject
{
  /**
   * Returns the value of the '<em><b>Src</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Src</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Src</em>' containment reference.
   * @see #setSrc(Location)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getConnection_Src()
   * @model containment="true"
   * @generated
   */
  Location getSrc();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getSrc <em>Src</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Src</em>' containment reference.
   * @see #getSrc()
   * @generated
   */
  void setSrc(Location value);

  /**
   * Returns the value of the '<em><b>Dst</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dst</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dst</em>' containment reference.
   * @see #setDst(Location)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getConnection_Dst()
   * @model containment="true"
   * @generated
   */
  Location getDst();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getDst <em>Dst</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dst</em>' containment reference.
   * @see #getDst()
   * @generated
   */
  void setDst(Location value);

  /**
   * Returns the value of the '<em><b>Length</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Length</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Length</em>' attribute.
   * @see #setLength(int)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getConnection_Length()
   * @model
   * @generated
   */
  int getLength();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getLength <em>Length</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Length</em>' attribute.
   * @see #getLength()
   * @generated
   */
  void setLength(int value);

  /**
   * Returns the value of the '<em><b>Gauge</b></em>' attribute.
   * The literals are from the enumeration {@link hu.bme.mit.temalab.railmap.railLinesMap.Gauge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Gauge</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gauge</em>' attribute.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.Gauge
   * @see #setGauge(Gauge)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getConnection_Gauge()
   * @model
   * @generated
   */
  Gauge getGauge();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.Connection#getGauge <em>Gauge</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gauge</em>' attribute.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.Gauge
   * @see #getGauge()
   * @generated
   */
  void setGauge(Gauge value);

} // Connection
