/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getLocation()
 * @model
 * @generated
 */
public interface Location extends EObject
{
} // Location
