/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Station Track Location</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation#getStation <em>Station</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation#getTrack <em>Track</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getStationTrackLocation()
 * @model
 * @generated
 */
public interface StationTrackLocation extends Location
{
  /**
   * Returns the value of the '<em><b>Station</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Station</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Station</em>' reference.
   * @see #setStation(Station)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getStationTrackLocation_Station()
   * @model
   * @generated
   */
  Station getStation();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation#getStation <em>Station</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Station</em>' reference.
   * @see #getStation()
   * @generated
   */
  void setStation(Station value);

  /**
   * Returns the value of the '<em><b>Track</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Track</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Track</em>' attribute.
   * @see #setTrack(int)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getStationTrackLocation_Track()
   * @model
   * @generated
   */
  int getTrack();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation#getTrack <em>Track</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Track</em>' attribute.
   * @see #getTrack()
   * @generated
   */
  void setTrack(int value);

} // StationTrackLocation
