/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Turnout End Location</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation#getTurnout <em>Turnout</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getTurnoutEndLocation()
 * @model
 * @generated
 */
public interface TurnoutEndLocation extends Location
{
  /**
   * Returns the value of the '<em><b>Turnout</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Turnout</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Turnout</em>' reference.
   * @see #setTurnout(Turnout)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getTurnoutEndLocation_Turnout()
   * @model
   * @generated
   */
  Turnout getTurnout();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation#getTurnout <em>Turnout</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Turnout</em>' reference.
   * @see #getTurnout()
   * @generated
   */
  void setTurnout(Turnout value);

  /**
   * Returns the value of the '<em><b>End</b></em>' attribute.
   * The literals are from the enumeration {@link hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEnd}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' attribute.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEnd
   * @see #setEnd(TurnoutEnd)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getTurnoutEndLocation_End()
   * @model
   * @generated
   */
  TurnoutEnd getEnd();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation#getEnd <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' attribute.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEnd
   * @see #getEnd()
   * @generated
   */
  void setEnd(TurnoutEnd value);

} // TurnoutEndLocation
