/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ui.tests;

import com.google.inject.Injector;
import hu.bme.mit.temalab.railmap.ui.internal.RailmapActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RailLinesMapUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RailmapActivator.getInstance().getInjector("hu.bme.mit.temalab.railmap.RailLinesMap");
	}

}
