/*
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ui;

import com.google.inject.Injector;
import hu.bme.mit.temalab.railmap.ui.internal.RailmapActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RailLinesMapExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(RailmapActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		RailmapActivator activator = RailmapActivator.getInstance();
		return activator != null ? activator.getInjector(RailmapActivator.HU_BME_MIT_TEMALAB_RAILMAP_RAILLINESMAP) : null;
	}

}
