/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.temalab.railmap.RailLinesMapRuntimeModule;
import hu.bme.mit.temalab.railmap.RailLinesMapStandaloneSetup;
import hu.bme.mit.temalab.railmap.ide.RailLinesMapIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RailLinesMapIdeSetup extends RailLinesMapStandaloneSetup {
  @Override
  public Injector createInjector() {
    RailLinesMapRuntimeModule _railLinesMapRuntimeModule = new RailLinesMapRuntimeModule();
    RailLinesMapIdeModule _railLinesMapIdeModule = new RailLinesMapIdeModule();
    return Guice.createInjector(Modules2.mixin(_railLinesMapRuntimeModule, _railLinesMapIdeModule));
  }
}
