/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap.impl;

import hu.bme.mit.temalab.railmap.railLinesMap.Connection;
import hu.bme.mit.temalab.railmap.railLinesMap.Gauge;
import hu.bme.mit.temalab.railmap.railLinesMap.Location;
import hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap;
import hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapFactory;
import hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage;
import hu.bme.mit.temalab.railmap.railLinesMap.Station;
import hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation;
import hu.bme.mit.temalab.railmap.railLinesMap.Turnout;
import hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEnd;
import hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class RailLinesMapPackageImpl extends EPackageImpl implements RailLinesMapPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass railLineMapEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass connectionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass turnoutEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass locationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stationTrackLocationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass turnoutEndLocationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum turnoutEndEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum gaugeEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private RailLinesMapPackageImpl()
  {
    super(eNS_URI, RailLinesMapFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link RailLinesMapPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static RailLinesMapPackage init()
  {
    if (isInited) return (RailLinesMapPackage)EPackage.Registry.INSTANCE.getEPackage(RailLinesMapPackage.eNS_URI);

    // Obtain or create and register package
    RailLinesMapPackageImpl theRailLinesMapPackage = (RailLinesMapPackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof RailLinesMapPackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new RailLinesMapPackageImpl());

    isInited = true;

    // Create package meta-data objects
    theRailLinesMapPackage.createPackageContents();

    // Initialize created meta-data
    theRailLinesMapPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theRailLinesMapPackage.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(RailLinesMapPackage.eNS_URI, theRailLinesMapPackage);
    return theRailLinesMapPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getRailLineMap()
  {
    return railLineMapEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getRailLineMap_MapName()
  {
    return (EAttribute)railLineMapEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRailLineMap_Stations()
  {
    return (EReference)railLineMapEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRailLineMap_Turnouts()
  {
    return (EReference)railLineMapEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getRailLineMap_Connections()
  {
    return (EReference)railLineMapEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStation()
  {
    return stationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getStation_Name()
  {
    return (EAttribute)stationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getStation_Tracks()
  {
    return (EAttribute)stationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getConnection()
  {
    return connectionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConnection_Src()
  {
    return (EReference)connectionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getConnection_Dst()
  {
    return (EReference)connectionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConnection_Length()
  {
    return (EAttribute)connectionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getConnection_Gauge()
  {
    return (EAttribute)connectionEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTurnout()
  {
    return turnoutEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTurnout_Name()
  {
    return (EAttribute)turnoutEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getLocation()
  {
    return locationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getStationTrackLocation()
  {
    return stationTrackLocationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getStationTrackLocation_Station()
  {
    return (EReference)stationTrackLocationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getStationTrackLocation_Track()
  {
    return (EAttribute)stationTrackLocationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getTurnoutEndLocation()
  {
    return turnoutEndLocationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getTurnoutEndLocation_Turnout()
  {
    return (EReference)turnoutEndLocationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getTurnoutEndLocation_End()
  {
    return (EAttribute)turnoutEndLocationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getTurnoutEnd()
  {
    return turnoutEndEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EEnum getGauge()
  {
    return gaugeEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public RailLinesMapFactory getRailLinesMapFactory()
  {
    return (RailLinesMapFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    railLineMapEClass = createEClass(RAIL_LINE_MAP);
    createEAttribute(railLineMapEClass, RAIL_LINE_MAP__MAP_NAME);
    createEReference(railLineMapEClass, RAIL_LINE_MAP__STATIONS);
    createEReference(railLineMapEClass, RAIL_LINE_MAP__TURNOUTS);
    createEReference(railLineMapEClass, RAIL_LINE_MAP__CONNECTIONS);

    stationEClass = createEClass(STATION);
    createEAttribute(stationEClass, STATION__NAME);
    createEAttribute(stationEClass, STATION__TRACKS);

    connectionEClass = createEClass(CONNECTION);
    createEReference(connectionEClass, CONNECTION__SRC);
    createEReference(connectionEClass, CONNECTION__DST);
    createEAttribute(connectionEClass, CONNECTION__LENGTH);
    createEAttribute(connectionEClass, CONNECTION__GAUGE);

    turnoutEClass = createEClass(TURNOUT);
    createEAttribute(turnoutEClass, TURNOUT__NAME);

    locationEClass = createEClass(LOCATION);

    stationTrackLocationEClass = createEClass(STATION_TRACK_LOCATION);
    createEReference(stationTrackLocationEClass, STATION_TRACK_LOCATION__STATION);
    createEAttribute(stationTrackLocationEClass, STATION_TRACK_LOCATION__TRACK);

    turnoutEndLocationEClass = createEClass(TURNOUT_END_LOCATION);
    createEReference(turnoutEndLocationEClass, TURNOUT_END_LOCATION__TURNOUT);
    createEAttribute(turnoutEndLocationEClass, TURNOUT_END_LOCATION__END);

    // Create enums
    turnoutEndEEnum = createEEnum(TURNOUT_END);
    gaugeEEnum = createEEnum(GAUGE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    stationTrackLocationEClass.getESuperTypes().add(this.getLocation());
    turnoutEndLocationEClass.getESuperTypes().add(this.getLocation());

    // Initialize classes and features; add operations and parameters
    initEClass(railLineMapEClass, RailLineMap.class, "RailLineMap", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRailLineMap_MapName(), ecorePackage.getEString(), "mapName", null, 0, 1, RailLineMap.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRailLineMap_Stations(), this.getStation(), null, "stations", null, 0, -1, RailLineMap.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRailLineMap_Turnouts(), this.getTurnout(), null, "turnouts", null, 0, -1, RailLineMap.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getRailLineMap_Connections(), this.getConnection(), null, "connections", null, 0, -1, RailLineMap.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stationEClass, Station.class, "Station", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStation_Name(), ecorePackage.getEString(), "name", null, 0, 1, Station.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStation_Tracks(), ecorePackage.getEInt(), "tracks", null, 0, 1, Station.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(connectionEClass, Connection.class, "Connection", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getConnection_Src(), this.getLocation(), null, "src", null, 0, 1, Connection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getConnection_Dst(), this.getLocation(), null, "dst", null, 0, 1, Connection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConnection_Length(), ecorePackage.getEInt(), "length", null, 0, 1, Connection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConnection_Gauge(), this.getGauge(), "gauge", null, 0, 1, Connection.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(turnoutEClass, Turnout.class, "Turnout", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTurnout_Name(), ecorePackage.getEString(), "name", null, 0, 1, Turnout.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(locationEClass, Location.class, "Location", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(stationTrackLocationEClass, StationTrackLocation.class, "StationTrackLocation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getStationTrackLocation_Station(), this.getStation(), null, "station", null, 0, 1, StationTrackLocation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getStationTrackLocation_Track(), ecorePackage.getEInt(), "track", null, 0, 1, StationTrackLocation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(turnoutEndLocationEClass, TurnoutEndLocation.class, "TurnoutEndLocation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getTurnoutEndLocation_Turnout(), this.getTurnout(), null, "turnout", null, 0, 1, TurnoutEndLocation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTurnoutEndLocation_End(), this.getTurnoutEnd(), "end", null, 0, 1, TurnoutEndLocation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(turnoutEndEEnum, TurnoutEnd.class, "TurnoutEnd");
    addEEnumLiteral(turnoutEndEEnum, TurnoutEnd.TOP);
    addEEnumLiteral(turnoutEndEEnum, TurnoutEnd.STRAIGHT);
    addEEnumLiteral(turnoutEndEEnum, TurnoutEnd.DIVERGENT);

    initEEnum(gaugeEEnum, Gauge.class, "Gauge");
    addEEnumLiteral(gaugeEEnum, Gauge.STANDARD);
    addEEnumLiteral(gaugeEEnum, Gauge.NARROW);
    addEEnumLiteral(gaugeEEnum, Gauge.BROAD);

    // Create resource
    createResource(eNS_URI);
  }

} //RailLinesMapPackageImpl
