/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap.impl;

import hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage;
import hu.bme.mit.temalab.railmap.railLinesMap.Station;
import hu.bme.mit.temalab.railmap.railLinesMap.StationTrackLocation;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Station Track Location</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.impl.StationTrackLocationImpl#getStation <em>Station</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.impl.StationTrackLocationImpl#getTrack <em>Track</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StationTrackLocationImpl extends LocationImpl implements StationTrackLocation
{
  /**
   * The cached value of the '{@link #getStation() <em>Station</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStation()
   * @generated
   * @ordered
   */
  protected Station station;

  /**
   * The default value of the '{@link #getTrack() <em>Track</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrack()
   * @generated
   * @ordered
   */
  protected static final int TRACK_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getTrack() <em>Track</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTrack()
   * @generated
   * @ordered
   */
  protected int track = TRACK_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StationTrackLocationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RailLinesMapPackage.Literals.STATION_TRACK_LOCATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Station getStation()
  {
    if (station != null && station.eIsProxy())
    {
      InternalEObject oldStation = (InternalEObject)station;
      station = (Station)eResolveProxy(oldStation);
      if (station != oldStation)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RailLinesMapPackage.STATION_TRACK_LOCATION__STATION, oldStation, station));
      }
    }
    return station;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Station basicGetStation()
  {
    return station;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStation(Station newStation)
  {
    Station oldStation = station;
    station = newStation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailLinesMapPackage.STATION_TRACK_LOCATION__STATION, oldStation, station));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getTrack()
  {
    return track;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTrack(int newTrack)
  {
    int oldTrack = track;
    track = newTrack;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailLinesMapPackage.STATION_TRACK_LOCATION__TRACK, oldTrack, track));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.STATION_TRACK_LOCATION__STATION:
        if (resolve) return getStation();
        return basicGetStation();
      case RailLinesMapPackage.STATION_TRACK_LOCATION__TRACK:
        return getTrack();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.STATION_TRACK_LOCATION__STATION:
        setStation((Station)newValue);
        return;
      case RailLinesMapPackage.STATION_TRACK_LOCATION__TRACK:
        setTrack((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.STATION_TRACK_LOCATION__STATION:
        setStation((Station)null);
        return;
      case RailLinesMapPackage.STATION_TRACK_LOCATION__TRACK:
        setTrack(TRACK_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.STATION_TRACK_LOCATION__STATION:
        return station != null;
      case RailLinesMapPackage.STATION_TRACK_LOCATION__TRACK:
        return track != TRACK_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (track: ");
    result.append(track);
    result.append(')');
    return result.toString();
  }

} //StationTrackLocationImpl
