/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap.impl;

import hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage;
import hu.bme.mit.temalab.railmap.railLinesMap.Turnout;
import hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEnd;
import hu.bme.mit.temalab.railmap.railLinesMap.TurnoutEndLocation;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Turnout End Location</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.impl.TurnoutEndLocationImpl#getTurnout <em>Turnout</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.impl.TurnoutEndLocationImpl#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TurnoutEndLocationImpl extends LocationImpl implements TurnoutEndLocation
{
  /**
   * The cached value of the '{@link #getTurnout() <em>Turnout</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTurnout()
   * @generated
   * @ordered
   */
  protected Turnout turnout;

  /**
   * The default value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected static final TurnoutEnd END_EDEFAULT = TurnoutEnd.TOP;

  /**
   * The cached value of the '{@link #getEnd() <em>End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd()
   * @generated
   * @ordered
   */
  protected TurnoutEnd end = END_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TurnoutEndLocationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RailLinesMapPackage.Literals.TURNOUT_END_LOCATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Turnout getTurnout()
  {
    if (turnout != null && turnout.eIsProxy())
    {
      InternalEObject oldTurnout = (InternalEObject)turnout;
      turnout = (Turnout)eResolveProxy(oldTurnout);
      if (turnout != oldTurnout)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT, oldTurnout, turnout));
      }
    }
    return turnout;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Turnout basicGetTurnout()
  {
    return turnout;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTurnout(Turnout newTurnout)
  {
    Turnout oldTurnout = turnout;
    turnout = newTurnout;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT, oldTurnout, turnout));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TurnoutEnd getEnd()
  {
    return end;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnd(TurnoutEnd newEnd)
  {
    TurnoutEnd oldEnd = end;
    end = newEnd == null ? END_EDEFAULT : newEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, RailLinesMapPackage.TURNOUT_END_LOCATION__END, oldEnd, end));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT:
        if (resolve) return getTurnout();
        return basicGetTurnout();
      case RailLinesMapPackage.TURNOUT_END_LOCATION__END:
        return getEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT:
        setTurnout((Turnout)newValue);
        return;
      case RailLinesMapPackage.TURNOUT_END_LOCATION__END:
        setEnd((TurnoutEnd)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT:
        setTurnout((Turnout)null);
        return;
      case RailLinesMapPackage.TURNOUT_END_LOCATION__END:
        setEnd(END_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RailLinesMapPackage.TURNOUT_END_LOCATION__TURNOUT:
        return turnout != null;
      case RailLinesMapPackage.TURNOUT_END_LOCATION__END:
        return end != END_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (end: ");
    result.append(end);
    result.append(')');
    return result.toString();
  }

} //TurnoutEndLocationImpl
