/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.railLinesMap;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rail Line Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap#getMapName <em>Map Name</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap#getStations <em>Stations</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap#getTurnouts <em>Turnouts</em>}</li>
 *   <li>{@link hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap#getConnections <em>Connections</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getRailLineMap()
 * @model
 * @generated
 */
public interface RailLineMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Map Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Map Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Map Name</em>' attribute.
   * @see #setMapName(String)
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getRailLineMap_MapName()
   * @model
   * @generated
   */
  String getMapName();

  /**
   * Sets the value of the '{@link hu.bme.mit.temalab.railmap.railLinesMap.RailLineMap#getMapName <em>Map Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Map Name</em>' attribute.
   * @see #getMapName()
   * @generated
   */
  void setMapName(String value);

  /**
   * Returns the value of the '<em><b>Stations</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.temalab.railmap.railLinesMap.Station}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stations</em>' containment reference list.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getRailLineMap_Stations()
   * @model containment="true"
   * @generated
   */
  EList<Station> getStations();

  /**
   * Returns the value of the '<em><b>Turnouts</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.temalab.railmap.railLinesMap.Turnout}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Turnouts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Turnouts</em>' containment reference list.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getRailLineMap_Turnouts()
   * @model containment="true"
   * @generated
   */
  EList<Turnout> getTurnouts();

  /**
   * Returns the value of the '<em><b>Connections</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.temalab.railmap.railLinesMap.Connection}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connections</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connections</em>' containment reference list.
   * @see hu.bme.mit.temalab.railmap.railLinesMap.RailLinesMapPackage#getRailLineMap_Connections()
   * @model containment="true"
   * @generated
   */
  EList<Connection> getConnections();

} // RailLineMap
