/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap;

import hu.bme.mit.temalab.railmap.AbstractRailLinesMapRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class RailLinesMapRuntimeModule extends AbstractRailLinesMapRuntimeModule {
}
