/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ui;

import hu.bme.mit.temalab.railmap.ui.AbstractRailLinesMapUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RailLinesMapUiModule extends AbstractRailLinesMapUiModule {
  public RailLinesMapUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
