/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ide;

import hu.bme.mit.temalab.railmap.ide.AbstractRailLinesMapIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RailLinesMapIdeModule extends AbstractRailLinesMapIdeModule {
}
