/**
 * generated by Xtext 2.20.0-SNAPSHOT
 */
package hu.bme.mit.temalab.railmap.ui.contentassist;

import hu.bme.mit.temalab.railmap.ui.contentassist.AbstractRailLinesMapProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RailLinesMapProposalProvider extends AbstractRailLinesMapProposalProvider {
}
